version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    requirements:
      - requirements.lock
      - requirements-dev.lock
      - pyproject.toml
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
