repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv tool run ruff check
        language: system
        types_or: [python, pyi]
      - id: black
        name: black
        entry: uv tool run black
        language: system
        types_or: [python]
        args: ["--check", "--diff"]
      - id: mypy
        name: mypy
        entry: uv tool run mypy
        language: system
        pass_filenames: false
        always_run: true
