name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Run ci-local script
        run: ./scripts/ci-local.sh --locked

      - name: Generate CycloneDX SBOM
        run: uv tool run --from cyclonedx-bom cyclonedx-py requirements requirements-dev.lock --pyproject pyproject.toml --of JSON --output-file sbom.cdx.json

      - name: Upload SBOM artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.python-version }}
          path: sbom.cdx.json
